### ISSUE TITLE
do not go commands

### ISSUE THREAD

**Issue by majovec** [larryTheCoder/SkyWarsForPE#1]
plugin works but do not go commands :(

**Comment by SzczepanPolska** [comment]
Nów final plugin?

**Comment by SzczepanPolska** [comment]
How final plugin?*

**Comment by majovec** [comment]
moment

**Comment by larryTheCoder** [comment]
Sorry guys i am not reply my plugin i am still making it..is someone can help me with this code

**Comment by larryTheCoder** [comment]
hey i am still fixing this plugin just wait
