### ISSUE TITLE
How to setup arena

### ISSUE THREAD

**Issue by bulutsun** [larryTheCoder/SkyWarsForPE#10]
I couldn't create arena. Can you explain this in a detailed way, my friend.

**Comment by larryTheCoder** [comment]
yes my friend

there is some tips thats u can use

**Comment by larryTheCoder** [comment]
How to create an arena -

1: You must create an arena by using this cmd [ /sw create {your arena name} ]

2: Reload the server and there will be an arena name that u created in logger

How to setup an Arena -

1: You must run a command [ /sw setup {Your Arena Name} ]

2: Your chat will be disabled and you can use the chat as cmd example:
 - help
-  enable [on/off]
With no "/"
if u done just say in the chat "done"

How to enable an arena -

1: GO trough no.2 instruction and do "enable true"

*****This game is inspired by ColorMatch Plugin*****

**Comment by larryTheCoder** [comment]
Is it work?
