### ISSUE TITLE
Game wont end

### ISSUE THREAD

**Issue by ElectroGamesYT** [larryTheCoder/SkyWarsForPE#104]
When someone kills someone, the person who is dead is still counted in the game

**Comment by CarrotSide** [comment]
just download the skywars plugin on poggit.pmmp.io this plugin was released 3 yrs ago but it supports the pocketmine your using meaning its old, so i recommend u the newest one on poggit

**Comment by larryTheCoder** [comment]
I added some debugging tools for me to understand ur issue more clearly. Perhaps you could run the arena again and upload the debug files located in skywars folder `/logs/[Arena Name].txt`
