### ISSUE TITLE
Server close when the i hit someone

### ISSUE THREAD

**Issue by CludyMento** [larryTheCoder/SkyWarsForPE#106]
every time I hit someone, the server will shut down.. and Idk why :/

**Comment by larryTheCoder** [comment]
Debug file?

**Comment by CludyMento** [comment]
um I can't find it... 
![skywars](https://user-images.githubusercontent.com/54499136/79697089-97a3c400-8278-11ea-85e2-941924e74705.PNG) unless I'm looking at a wrong folder

**Comment by larryTheCoder** [comment]
Huh, this is odd, are you using the latest version? If so, then just try to add a `logs` folder and try running it again. Its working fine here

**Comment by CludyMento** [comment]
ye I'm using the latest version and I added a **logs** folder but it still doesn't work

**Comment by larryTheCoder** [comment]
Probably because you are using Linux OS. I will mark this as an issue

**Comment by CludyMento** [comment]
Linux OS? um no. I'm using windows 10

**Comment by larryTheCoder** [comment]
That pocketmine server you are hosted in, are in Windows 10?

**Comment by CludyMento** [comment]
yes

**Comment by XuBamboo** [comment]
I have the same problem
