### ISSUE TITLE
Crash on Death

### ISSUE THREAD

**Issue by Altamash347** [larryTheCoder/SkyWarsForPE#113]
Whenever I am Dying, its crashing. I thought that it might be Crashing because of Spectater mode so I turned it off but its still crashing, Please Fix it soon

**Comment by larryTheCoder** [comment]
And this is where the logs should be used. Please do me a favor, send me the error and your arena logs as well located in `/logs`

**Comment by Altamash347** [comment]
ok Let me crash again

**Comment by Altamash347** [comment]
Nvm it is not crashing in the latest but there is another bug im closing this issue and opening a new one
