### ISSUE TITLE
Libasynql problem.

### ISSUE THREAD

**Issue by towuk118** [larryTheCoder/SkyWarsForPE#116]
![image](https://user-images.githubusercontent.com/28830162/88676091-58490700-d0f4-11ea-98c5-5e1a7585c197.png)
![image](https://user-images.githubusercontent.com/28830162/88676105-5c752480-d0f4-11ea-9568-8d09025c3e8e.png)
![image](https://user-images.githubusercontent.com/28830162/88676117-6008ab80-d0f4-11ea-9fd8-5127a1e593f0.png)

**Comment by larryTheCoder** [comment]
Its funny to see how my plugin still gets loaded even when the plugin failed to enable libasyncsql
