### ISSUE TITLE
How to setup a sign?

### ISSUE THREAD

**Issue by Itachitard** [larryTheCoder/SkyWarsForPE#119]
Can you please give me an example on how to setup a sign?

A photo or something

**Comment by Itachitard** [comment]
Can you please give me an example? Its been 3 days

**Comment by larryTheCoder** [comment]
Well sorry for waiting a very obnoxious amount of time, here is a simple brief of example on how to setup the sign:
1. Run `/sw settings`
2. Click on the "Set Join Sign Location"
![image](https://user-images.githubusercontent.com/15889642/91461015-178f0a00-e8bb-11ea-9055-fd65c948ff0c.png)
3. Break a block with your Blaze Rod item in your inventory.

There we go, you have setup one
