### ISSUE TITLE
Sign Bug

### ISSUE THREAD

**Issue by Itachitard** [larryTheCoder/SkyWarsForPE#120]
I setup the signs but the Arenas got disabled,all of them are enabled but the they're are basically disabled at all

**Comment by laigelplayz** [comment]
Happens to me aswell....

**Comment by laigelplayz** [comment]
Sign Isnt Working Please Fix I need it

**Comment by larryTheCoder** [comment]
Im aware about this issue, I will push a fix for the bugs today

**Comment by larryTheCoder** [comment]
_Yeah I know its 9 days now, I am really are busy these days_
