### ISSUE TITLE
Libasynql Library Installation.

### ISSUE THREAD

**Issue by MineGuy112** [larryTheCoder/SkyWarsForPE#124]
Hey there!

I've been intrigued by your plugins and I'm very moved by your cause to let paid plugins die.

I've just come here to discuss a small issue. You've probably guessed it has something to do with libasynql.
It's just that the plugin won't work without it and I don't know how to install it on my server...

If you could please help me out or make a version of the plugin which doesn't require the libasynql I'd be in your debt.

Thanks for reading!

-Miney

**Comment by larryTheCoder** [comment]
The plugin requires devirions to work properly, put [devirions phar file](https://poggit.pmmp.io/r/61892/DEVirion_dev-33.phar) into /plugins and download [libasynql](https://poggit.pmmp.io/r/102077/libasynql_dev-137.phar) and place them into `/virions`, then it will work

**Comment by MineGuy112** [comment]
Aight Thank You So Very Much!

Lookin' forward to working with you..

Catch ya later,

-Miney
