### ISSUE TITLE
It isn't working internal server error when making any command arena.php need to be fixed

### ISSUE THREAD

**Issue by mr-zinkil** [larryTheCoder/SkyWarsForPE#127]
Title

**Comment by larryTheCoder** [comment]
Yeah the problem seems to be "You are trying to config the arena but it doesn't works". The reason is, there is no way you can configure this in game, you need to configure this arena by bare hand in /arenas file, but if you want this feature to be available, you can wait :)

**Comment by benda95280** [comment]
@larryTheCoder I don't wanna open an issue to say that words, so let me say it here : 
Thanks you for your work ! 👍

**Comment by larryTheCoder** [comment]
Not a big deal haha
