### ISSUE TITLE
if there is Any FREE server's that can be used for this plugin

### ISSUE THREAD

**Issue by larryTheCoder** [larryTheCoder/SkyWarsForPE#13]
Help is very much appreciated

**Comment by Adam1609** [comment]
I could help you test all plugin

**Comment by larryTheCoder** [comment]
Thank you what your server port?

**Comment by Adam1609** [comment]
It is play.redvn.xyz Port 19132

**Comment by larryTheCoder** [comment]
i will check it later my Username is larryZ00p or larryZ00 or MrCrazy101

**Comment by Adam1609** [comment]
But, execute command not work!

**Comment by Adam1609** [comment]
And also, i don't know how to use this plugin, seem setmoney (amount) is error

**Comment by larryTheCoder** [comment]
Bug fixed

**Comment by Adam1609** [comment]
Ok, I could help you test if you show me how to setup a join sign

**Comment by larryTheCoder** [comment]
Uh? You say u know how to setup it? Its just like you setup an ColorMatch Arena
This plugin is an colormatch but written for skywars

**Comment by larryTheCoder** [comment]
there is setspawn

**Comment by Adam1609** [comment]
Oh, that's why..... but you dont have plugin.yml ha????

**Comment by larryTheCoder** [comment]
umm there is at [here](https://github.com/larryTheCoder/SkyWarsForPE/tree/master/src/SkyWars)

**Comment by Adam1609** [comment]
I saw you go to my server, but my staff told me that your plugin had a problem. Setting up arena was done but couldn't join!

**Comment by larryTheCoder** [comment]
if there is any exception in logger or screenshot?

**Comment by larryTheCoder** [comment]
OR did the Console say `[21:26:07] [Server thread/INFO]: [SkyWars] default.yml - is disabled`

**Comment by larryTheCoder** [comment]
Ahm did your server online?

**Comment by Mrfanman345** [comment]
Try downloading Pocket Server from the Google play store.

**Comment by NycuR0** [comment]
@larryTheCoder I'm here.
