### ISSUE TITLE
Problem in Spectator Mode

### ISSUE THREAD

**Issue by twk1024** [larryTheCoder/SkyWarsForPE#131]
Hi.

When players die, that player would spectate other players.
But the problem is when players are in the Spectator mode, they are still able to hit other survived players and open the chests.

So, that means Spectators can interrupt the playing of other players.

**Comment by larryTheCoder** [comment]
Thanks for opening this issue, your problem has been identified and will be fixed in a few hours.

**Comment by larryTheCoder** [comment]
The current version should fix your issue, If there is any problems, feel free to open another issue

**Comment by twk1024** [comment]
> The current version should fix your issue, If there is any problems, feel free to open another issue

Thanks. It works well now.
