### ISSUE TITLE
Internal Server Error when creating an arena and setting its spawn

### ISSUE THREAD

**Issue by SkyGamingPHYT** [larryTheCoder/SkyWarsForPE#134]
Welp
![Screenshot_20201208-211213](https://user-images.githubusercontent.com/71017108/101488794-031edb00-399b-11eb-84df-c96779a95f57.png)
![Screenshot_20201208-211223](https://user-images.githubusercontent.com/71017108/101488821-0b771600-399b-11eb-8abf-17f4223cb58c.png)
![Screenshot_20201208-211254](https://user-images.githubusercontent.com/71017108/101488525-ade2c980-399a-11eb-8a3b-c974aaca8e57.png)

Might be the plugin is having problems with other plugins

**Comment by larryTheCoder** [comment]
This error has nothing todo with this plugin.
