### ISSUE TITLE
How do you setup the kits?

### ISSUE THREAD

**Issue by LuciferVerma** [larryTheCoder/SkyWarsForPE#136]
Hey. How do you add kits? 
I added kits in my EasyKits. But kits aren't showing in arenas. How do you setup it? 
Can you explain it briefly?

**Comment by larryTheCoder** [comment]
First, your kit must have `sw.internal.*` permission set. 

Example:
![image](https://user-images.githubusercontent.com/15889642/101808956-f1cbff00-3b51-11eb-85f0-2b732a128248.png)

 this * can be any string.

**Comment by LuciferVerma** [comment]
Thanks you Imma go test
