### ISSUE TITLE
[easykit] now called data

### ISSUE THREAD

**Issue by TOWUK** [larryTheCoder/SkyWarsForPE#138]
https://youtu.be/6zHTQ0uwr-A
in wait cages kits not called for easykits!

**Comment by LuciferVerma** [comment]
When you are making the kits add this permission into it

https://user-images.githubusercontent.com/15889642/101808956-f1cbff00-3b51-11eb-85f0-2b732a128248.png

**Comment by larryTheCoder** [comment]
https://github.com/larryTheCoder/SkyWarsForPE/wiki/Using-EasyKits

**Comment by TOWUK** [comment]
> https://github.com/larryTheCoder/SkyWarsForPE/wiki/Using-EasyKits

I decided to insert the configuration from the previous version of easy kits into the new one... Okay, I'll try again!
