### ISSUE TITLE
[feature request] forcestart game/arena

### ISSUE THREAD

**Issue by TOWUK** [larryTheCoder/SkyWarsForPE#140]
Please add the command **/sw force start** (**/sw fs**) command if you clicked on the sign and are waiting for the game or **/sw forcestart ArenaName** to start another arena...

**Comment by TOWUK** [comment]
and "chest kit" not gived in start game
![image](https://user-images.githubusercontent.com/28830162/102460302-d97b4900-4057-11eb-85cf-ab7243026a0b.png)

**Comment by larryTheCoder** [comment]
Force start arena can be a bit hard, but I will do what is can. For chestKit option, there is not chestKit option, all the flags is unusable in this implementation. My EasyKit API is a hack to get around items.

**Comment by larryTheCoder** [comment]
For your feature request, it has been done, but for the chest kit, it will be done in the next update.
