### ISSUE TITLE
ASkyBlock-Nukkit

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/SkyWarsForPE#15]
Hi @larryTheCoder . Thanks for creating epic plugins. You can create and for Nukkit ? :)

And BlockParty or 1vs1 and 2vs2 and other for Nukkit from Bukkit ? :)

Thanks :)

**Comment by larryTheCoder** [comment]
I will try the best 👍

**Comment by NycuRO** [comment]
:>

**Comment by larryTheCoder** [comment]
i will make an EggWars Plugin! And i will sure that it will works!!

**Comment by NycuRO** [comment]
@larryTheCoder Ok ,thanks. But you can continue with SkyWars ( Like SkyWars X plugin PC ) and ASkyBlock ,please?

**Comment by larryTheCoder** [comment]
Sure

**Comment by NycuRO** [comment]
Schematic and Challanges . I need commands ,not database.

**Comment by larryTheCoder** [comment]
I am developing Schematic please wait =)

**Comment by NycuRO** [comment]
Ok , but i need commands @larryTheCoder with achievments :)

**Comment by NycuRO** [comment]
@larryTheCoder Ready? :)

**Comment by larryTheCoder** [comment]
@NycuRO Schematic - done Commands - 80% done Database - Developing

**Comment by NycuRO** [comment]
I don't need database. @larryTheCoder

**Comment by NycuRO** [comment]
Pre-Release please post :)

**Comment by larryTheCoder** [comment]
I just done my Pre-Release

**Comment by NycuRO** [comment]
@larryTheCoder You can post code? ..
