### ISSUE TITLE
[Suggestion] Set players gamemode to original gamemode when they leave the queue 

### ISSUE THREAD

**Issue by KadTheHunter** [larryTheCoder/SkyWarsForPE#150]
When players join the queue and subsequently quit, they get set to survival mode regardless of what their original gamemode is.
I tried this in both Creative and Adventure modes (two modes my players may be in when joining the queue) and still got put in survival when I left the queue. This is a pretty big issue for servers with non-survival hubs and those that don't allow players access to gamemode commands, which is quite common.

**Comment by larryTheCoder** [comment]
Noted, this will be the next change in the next update.

**Comment by larryTheCoder** [comment]
To clarify, there should be a configuration to this in config.yml, I hope you didn't miss that.
