### ISSUE TITLE
Feature That Should be added 

### ISSUE THREAD

**Issue by RealXoctic** [larryTheCoder/SkyWarsForPE#152]
Can you add soulwells like hypiel in which by each kill you get 5 souls and the soul well is like crates and it gives your permission to use kits or cages please if you can please do it is a very humble request from my side

**Comment by larryTheCoder** [comment]
This is a bit too much for an opensource SkyWars plugin. Honestly I do not want this plugin to be at the point where I cannot create a bit income for this project, but you can commission me to create an addon for that. I'm sorry to say but this is the purpose of this project.

**Comment by BLAST1718** [comment]
> Can you add soulwells like hypiel in which by each kill you get 5 souls and the soul well is like crates and it gives your permission to use kits or cages please if you can please do it is a very humble request from my side

cant u do it urself?

**Comment by RealXoctic** [comment]
ok thanks for your reply i think i can make an addon for it myself if i didnt i will definetly ask you to do it on commision
