### ISSUE TITLE
Game end event plz

### ISSUE THREAD

**Issue by dragonkid608** [larryTheCoder/SkyWarsForPE#156]
im trying to make a autogg i just need to know what is the death, win and game end event plz

**Comment by dragonkid608** [comment]
?

**Comment by larryTheCoder** [comment]
I will document it later, don't really have the time to do it now. But to answer your question

## Death Event Function
https://github.com/larryTheCoder/SkyWarsForPE/blob/master/src/larryTheCoder/arena/EventListener.php#L224

## Win Game Function
It is hardcoded in my task, but you can add your own custom ones after this line
https://github.com/larryTheCoder/SkyWarsForPE/blob/master/src/larryTheCoder/arena/task/SkyWarsTask.php#L96

## Game End Event Function
https://github.com/larryTheCoder/SkyWarsForPE/blob/master/src/larryTheCoder/arena/ArenaImpl.php#L215
