### ISSUE TITLE
Discord Notify

### ISSUE THREAD

**Issue by callumrawlinson** [larryTheCoder/SkyWarsForPE#157]
hi @larryTheCoder  Can i add a discord notification when games start. It will send a message to discord when a games starts and when it ends and who won. I know how to do this but wanted your permission

thanks callum

**Comment by callumrawlinson** [comment]
@larryTheCoder

**Comment by callumrawlinson** [comment]
hello?

**Comment by larryTheCoder** [comment]
Well this is a bit redundant to add
