### ISSUE TITLE
Libasynql not found

### ISSUE THREAD

**Issue by pushkarI** [larryTheCoder/SkyWarsForPE#161]
[
![Screenshot_20210403-134119](https://user-images.githubusercontent.com/78496510/113472683-78e70f00-9482-11eb-8fd4-faf6e9b74ce5.jpeg)
](url)

**Comment by larryTheCoder** [comment]
Are you sure you are downloading the right phar? [Here is the download link](https://poggit.pmmp.io/r/119795/SkyWarsForPE_dev-113.phar)

**Comment by pushkarI** [comment]
Done
