### ISSUE TITLE
Error with fireworks 

### ISSUE THREAD

**Issue by DragonfireHD** [larryTheCoder/SkyWarsForPE#165]
Argument 3 passed to larryTheCoder\utils\fireworks\entity\FireworksRocket::__construct() must be an instance of larryTheCoder\utils\fireworks\Fireworks or null, instance of BlockHorizons\Fireworks\item\Fireworks given, called in phar:///home/minecraft/pocketmine.phar/src/pocketmine/entity/Entity.php on line 381" (EXCEPTION) in "plugins/SkyWarsForPE_dev-113.phar/src/larryTheCoder/utils/fireworks/entity/FireworksRocket" at line 48

**Comment by larryTheCoder** [comment]
This problem will happen when you try to register two same Fireworks entities on different plugins. In this case BlockHorizons. I will propose a fix for this.
