### ISSUE TITLE
onPlayerQuit

### ISSUE THREAD

**Issue by starterdragon** [larryTheCoder/SkyWarsForPE#19]
there's an error when players join an arena, then quit on the server...

the error only shows when they Join again.

**Comment by starterdragon** [comment]
I fixed this on my pc..

	public function onPlayerQuit(PlayerQuitEvent $ev) {
		$p = $ev->getPlayer();
		if ($this->arena->inArena($p)) {
			$this->plugin->getPlayerArena($p)->leaveArena($p);
            return;
        }
	}

dont forget the Class PlayerQuitEvent

**Comment by starterdragon** [comment]
I added that on Arena Listener

**Comment by larryTheCoder** [comment]
well i dont know about that XD. thanks for telling me about that

**Comment by NycuR0** [comment]
And now exist this issue? 

@starterdragon
