### ISSUE TITLE
work?

### ISSUE THREAD

**Issue by Driesboy** [larryTheCoder/SkyWarsForPE#2]

**Comment by larryTheCoder** [comment]
no its not working yet

**Comment by larryTheCoder** [comment]
maybe you can ask people to fix this i think i will release it tomorrow or today 1.6 Pre-Release-10

**Comment by larryTheCoder** [comment]
here you go https://goo.gl/zJ5WoS **ITS MAY COINTAIN BUGS ITS IS IN YOUR CHOICE**
