### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by skull3x** [larryTheCoder/SkyWarsForPE#21]
This gives me trouble when I execute the /sw command

```php
public function getMsg($key) {
$msg = str_replace("&","§",$this->msg->get($key));
return $msg;
}
```
![image](https://cloud.githubusercontent.com/assets/15986189/21308231/03a8d592-c5a7-11e6-9b72-fcb53045b9b3.png)

**Comment by NycuR0** [comment]
Steps to reproduce? 

@larryTheCoder Can i help you?

**Comment by xXNiceAssasinl0** [comment]
Same prob
