### ISSUE TITLE
you can write bedwars?

### ISSUE THREAD

**Issue by XakerS** [larryTheCoder/SkyWarsForPE#3]
???

**Comment by larryTheCoder** [comment]
If you can. I cant because its too hard...SkyWars is easy to write than BedWars maybe u can give me some old bedwars plugin or something in GitHub... I can help

**Comment by Skull3x** [comment]
Yeah, I agree. Plus BedWars is a large project to work on and would require more than one person to do "as In write entirely" so taking a curent BedWars plugin from GitHub and extending it would be wise

**Comment by Skull3x** [comment]
I could help if you need it

**Comment by XakerS** [comment]
I suggest you create an account in social networks vk.com there will be easier to communicate
We have enough intelligent developers

Mr profile for contact: [click](vk.com/xaker_ok_go)

**Comment by XakerS** [comment]
Paste in browser vk.com/xaker_ok_go

**Comment by larryTheCoder** [comment]
i see there is a people write BedWars https://github.com/Survingo/BedWarsPE

**Comment by larryTheCoder** [comment]
ok but what BedWars do...i played it its just like EggWars but there is bed is this game is same like EggWars

**Comment by larryTheCoder** [comment]
Next update, arena 1/2 loading will be implement

**Comment by XakerS** [comment]
Whoopi :3

**Comment by larryTheCoder** [comment]
For now i had found 2 bedwars plugins https://github.com/Bluplayz/BedwarsPE/tree/master/src/Bluplayz
And
https://github.com/Ragnok123/BedWarsPE

**Comment by XakerS** [comment]
2 bedwars ,old api

**Comment by larryTheCoder** [comment]
@XakerS Sorry if i announced the unecessary `EggWars plugin.` Lets start again 
@XakerS I had a little problem in that `I am bad in communicating` today i reliezed that i cant work in this project by my own, so dan @XakerS @Skull3x and @NycuRO join my team?

**Comment by NycuRO** [comment]
@larryTheCoder Ok, i can help. But i don't know very well java .. And i don't know improve :/

**Comment by NycuRO** [comment]
more special is skyblock ,please develop this plugin ,is very very good and all person need.

**Comment by NycuR0** [comment]
@larryTheCoder Sure!
