### ISSUE TITLE
Larry?

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/SkyWarsForPE#31]
Larry? You're still alive? Wow.

Can you send me a message on discord? NycuRO#6842

**Comment by NycuRO** [comment]
@larryTheCoder

**Comment by larryTheCoder** [comment]
`You still alive?` are you kidding me? Of course I am xD

**Comment by treehousemc1** [comment]
@larryTheCoder @IarryTheCoder is this plugin still alive :D
