### ISSUE TITLE
Sign could not work properly

### ISSUE THREAD

**Issue by A354-PH** [larryTheCoder/SkyWarsForPE#34]
Everytime i use joinsign, it wont show it

**Comment by larryTheCoder** [comment]
You setup it correctly?

**Comment by A354-PH** [comment]
Yes but everytime i do it, it just shows a plain sign.....

**Comment by A354-PH** [comment]
Its enabled

**Comment by larryTheCoder** [comment]
Tested it, and its not really working, somehow :thinking: 

Thanks for submitting this issue.

**Comment by AbisGameryt** [comment]
THIS ISNOT FIXED PLEASE HELP
