### ISSUE TITLE
Add NPC library

### ISSUE THREAD

**Issue by SuperKali** [larryTheCoder/SkyWarsForPE#38]
i've tried to use /sw npc but isn't appared nothing!
you can say to me how work this?

**Comment by larryTheCoder** [comment]
NPC is not **available**, I forgot to remove it from readme.
The reason why I remove it from the code, its because this could be sold separately from the plugin itself, we will gonna release it soon.

**Comment by larryTheCoder** [comment]
Sorry for what I just said, I will going to add it soon
