### ISSUE TITLE
Implement scoreboards in-game

### ISSUE THREAD

**Issue by Reflyansyah** [larryTheCoder/SkyWarsForPE#39]
Please Use the Scoreboard API

<!> A little discussion !
What are the Terms for collaborated ?

**Comment by larryTheCoder** [comment]
Well, no, I still collaborate with Hyrule minigames :/ but most of the core has been deleted. 
But nope.
PS: I will add scoreboards API soon

**Comment by larryTheCoder** [comment]
Github is having outage currently, can't do much

**Comment by refly2119** [comment]
Can I request your Gamertag
