### ISSUE TITLE
Plzz help

### ISSUE THREAD

**Issue by moch09** [larryTheCoder/SkyWarsForPE#48]
why if the server is restarted the plugin error

**Comment by larryTheCoder** [comment]
Well I dont really recommended to restart the server... as what bukkit does
So just don't do it

**Comment by moch09** [comment]
then what should I do?

**Comment by larryTheCoder** [comment]
Did you do /reload? Dont reload the server, just stop it then start it again

**Comment by MrNoob6969** [comment]
Who use reload nowadays.

**Comment by moch09** [comment]
I will try it :)

**Comment by moch09** [comment]
why if I can't get out of the game in the game but I tap go back lobby

**Comment by MrNoob6969** [comment]
Be sure to leave a star!

**Comment by larryTheCoder** [comment]
Welp

**Comment by moch09** [comment]
Yeah

**Comment by moch09** [comment]
You have wa?

**Comment by larryTheCoder** [comment]
wa what?

**Comment by moch09** [comment]
Whatsapp

**Comment by larryTheCoder** [comment]
Hmm no lol

**Comment by moch09** [comment]
Wkwkwk Facebook?

**Comment by larryTheCoder** [comment]
I dont have social medias

**Comment by moch09** [comment]
Ok thx

**Comment by larryTheCoder** [comment]
why if I can't get out of the game in the game but I tap go back lobby.

What do you mean by that? You can't leave the game by /leave?

**Comment by MrNoob6969** [comment]
yeah. /leave doesn't works.
