### ISSUE TITLE
FakeHuman return nulled when the level is not generated

### ISSUE THREAD

**Issue by moch09** [larryTheCoder/SkyWarsForPE#49]
Larry please help fake human bug

**Comment by moch09** [comment]
the bug is on npc / fakehuman line 209 and yes on the console :(

**Comment by larryTheCoder** [comment]
Hmm can you send me the whole error

**Comment by moch09** [comment]
Hmm can you send me the whole error

**Comment by moch09** [comment]
Sorry

**Comment by moch09** [comment]
Wait

**Comment by moch09** [comment]
https://www.photobox.co.uk/album/temporary

**Comment by larryTheCoder** [comment]
![image](https://user-images.githubusercontent.com/15889642/50515746-6cc0ba00-0ae1-11e9-8bc4-856b285927d8.png)
You can just upload it trough github...

**Comment by moch09** [comment]
Ouhh

**Comment by moch09** [comment]
have you seen the bug Larry?

**Comment by larryTheCoder** [comment]
Hmm yes, I will fix it soon™

**Comment by moch09** [comment]
ok whether the return value bug with leave arena will be fixed?

**Comment by larryTheCoder** [comment]
Its has been noticed too, well its will be fixed anytime soon, just wait

**Comment by moch09** [comment]
I hope you can fix it tomorrow and upload it

**Comment by MrNoob6969** [comment]
You have to wait. You're getting it free afterall.

**Comment by AeterniaNetwork** [comment]
Aaaaaa

**Comment by larryTheCoder** [comment]
The new PedestalManager in my latest build will fix this issue and the skin as well, sorry for waiting too long lol
