### ISSUE TITLE
Server crash when a player wins

### ISSUE THREAD

**Issue by Poustmal** [larryTheCoder/SkyWarsForPE#52]
Just setup a skywar arena(it works fine),then join to the sw arena and wait after someone wins the match,and the server will crash instantly.My server didn't throw errors,it just closed and I'm using the latest version of the plugin(that after 1 day ago)and pocketmine 3.5.2 with 1.8.0 version.

**Comment by larryTheCoder** [comment]
Well, I gonna ask. Did the server crash or your client crash?

**Comment by Poustmal** [comment]
The server crashed not the client.

**Comment by AeterniaNetwork** [comment]
Please send the crash log

**Comment by Poustmal** [comment]
Ok works fine now,I'll reopen the issue if I have problems.
