### ISSUE TITLE
Ultimate Report

### ISSUE THREAD

**Issue by AeterniaNetwork** [larryTheCoder/SkyWarsForPE#53]
1. Enchantment 14 ?
```
[09:51:53] [Server thread/INFO]: [SkyWars] Starting SkyWarsForPE modules...
[09:51:53] [Server thread/INFO]: >> Invalid chests.yml: enchantment `14` in `level-2` doesn't appears to be exists.
[09:51:53] [Server thread/INFO]: [SkyWars] Loaded chest random configuration.
```

2. Tanda Menghilang
Korang Bisa Tengok Disini : https://streamable.com/fkq7w

• Gunakan Bahasa Malaysia / Indonesia Jika Diperlukan !

Os : backslashlinux
Php : 7.2
PMMP : 3.5.3
More : Proxy Server. Idea From Herojhjh Since 2017, And Thank You To [ LarryTheCoder ] Since 2018

**Comment by larryTheCoder** [comment]
The first one, enchantment 14 is a Looting enchantment, the enchantment is not registered to the pocketmine yet. Well if you want to use that enchantment, I recommend using [TeaSpoon](https://github.com/CortexPE/TeaSpoon). Anyways, its not a big issue.

Second one, well I can't really tell about that, Try restarting your server or remove and replace the signs back.

**Comment by AeterniaNetwork** [comment]
Problem 2
1. It remains the same after restarting the server
When you finish playing the sign disappears again

•> Refly - Kun
