### ISSUE TITLE
[Enhancement] Kits

### ISSUE THREAD

**Issue by GooglePlugin** [larryTheCoder/SkyWarsForPE#57]
We can add some kits to improve the game.  For example: Enderpearls.

**Comment by larryTheCoder** [comment]
The kits aren't ready yet. The kits have its own API which means you can build a custom kit based on what you want to, Here something: "Slowdown, Fireworks, Mobs, Arrows Rain, etc"
Its not ready yet, as I mentioned so please wait

**Comment by GooglePlugin** [comment]
Okay, I am looking forward to it.

**Comment by Reflyansyah** [comment]
Hmm
