### ISSUE TITLE
Extraction Error - When enabling arena

### ISSUE THREAD

**Issue by CryptoKey98** [larryTheCoder/SkyWarsForPE#63]
![capture](https://user-images.githubusercontent.com/30509839/53694793-e2126a80-3d70-11e9-9f97-4724083157ab.PNG)

**Comment by CryptoKey98** [comment]
I will upload a video shortly.

**Comment by larryTheCoder** [comment]
I know this is kinda old but can you make sure that your server has the permission to change the file?
Or is that directory exists?
