### ISSUE TITLE
Team mode?

### ISSUE THREAD

**Issue by GamerDaniel3000** [larryTheCoder/SkyWarsForPE#67]
How can I set the Arena Mode to Teams?

**Comment by larryTheCoder** [comment]
Actually, its not implemented yet D:
There is a lot of things that isn't done so please wait

**Comment by larryTheCoder** [comment]
Can you actually try to contact me through discord if you has questions?

**Comment by GamerDaniel3000** [comment]
What is you dc tag?

**Comment by larryTheCoder** [comment]
Just join this server: https://discord.gg/sVgwJW

**Comment by larryTheCoder** [comment]
Team mode is now available, but it is still on bleeding phase, however I will close this issue as it is no longer related
