### ISSUE TITLE
Corrupt world

### ISSUE THREAD

**Issue by ItsMeBman** [larryTheCoder/SkyWarsForPE#75]
When I try go to the world by teleporting there ipwith multiworld or clicking on the Skywars sign, it kicks me with the reason :”Internal Server Error”
Sometimes my server even crashes and does not turn back on.
Please tell me how to fix this!

**Comment by larryTheCoder** [comment]
Reset your world, and try to reset the directory of SkyWarsForPE worlds folder. And then restart again the server. If your server cannot load the level. Its mean that your world is corrupted. I'm sorry. This is not my issue. Your world is having corruption. I expect pmmp is behind all of this

**Comment by ItsMeBman** [comment]
Sorry to bother your again but how would I do that?
