### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by RealCaptainGaming** [larryTheCoder/SkyWarsForPE#78]
So i have the 1.9.3 beta version and its the 36# dev and its not working idk why

**Comment by GamerDaniel3000** [comment]
Minecraft 1.11.4 is out....

**Comment by DiagonalPRO** [comment]
Why would you use an outdated version of mcpe lol? Download the updated one from here if you don't have it purchased. mcpe-monster.com

**Comment by larryTheCoder** [comment]
This plugin only support latest version of minecraft and pmmp 🤦‍♂
