### ISSUE TITLE
Implement kits for SkyWars game

### ISSUE THREAD

**Issue by ViruZzInGame** [larryTheCoder/SkyWarsForPE#81]
Skywars kit don't work "command not exist"

**Comment by DiagonalPRO** [comment]
Kits are not implemented yet. Frist of all you need to have kitui to work.

**Comment by DiagonalPRO** [comment]
Stay tune for updates.

**Comment by ViruZzInGame** [comment]
Oh Okey good!

**Comment by larryTheCoder** [comment]
> Stay tune for updates.

Indeed, the next update will be the Kits update.
