### ISSUE TITLE
Cages Not Working

### ISSUE THREAD

**Issue by TiredCueia** [larryTheCoder/SkyWarsForPE#82]
When I do /sw cage and I press the default cage it kicks me for "Internal Server Error" Help me please

**Comment by DiagonalPRO** [comment]
Hello, TiredCueia. It's me TheMinerRange. To use /sw cage you have to create some in the SkyWars folder. If its not working or you did smth wrong thats means cages are not implemented yet.

**Comment by TiredCueia** [comment]
Ok thanks!

Στις Παρ, 7 Ιουν 2019, 11:01 ο χρήστης DiagonalPRO <notifications@github.com>
έγραψε:

**Comment by GrapeFuitberries** [comment]
Help me!!  why the heck If im done playing i teleported World not my Other World Pls help And kits isn't working It said Commandfail do /help Some things like that HELP!!!!!!  Mayday

**Comment by GrapeFuitberries** [comment]
Help me!!  why the heck If im done playing i teleported World not my Other World Pls help And kits isn't working It said Commandfail do /help Some things like that HELP!!!!!!  Mayday And Cage to Broken

**Comment by larryTheCoder** [comment]
See you again in 5 more months

**Comment by Johnsonk79** [comment]
@GrapeFuitberries it teleports you to the default world, just set the world you want to get teleported to the default world...

**Comment by larryTheCoder** [comment]
I would say that this issue is fixed in the latest version, can someone confirm about this?
