### ISSUE TITLE
Lang Russian - ru_RU

### ISSUE THREAD

**Issue by No4NaMe** [larryTheCoder/SkyWarsForPE#91]
Dear developer, please add my translation Russian ru_RU encoding UTF-8 link: [https://mcraft.pw/ru_RU.yml](url)

after line 119 add this:
$this->saveResource("language/ru_RU.yml");
[https://github.com/larryTheCoder/SkyWarsForPE/blob/master/src/larryTheCoder/SkyWarsPE.php](url)

**Comment by larryTheCoder** [comment]
Huh, actually the locales are not done yet xD. Most of the stuffs need to be checked again and probably gets removed. Sorry the work you've done but I appreciate the effort.
