### ISSUE TITLE
Win Crash

### ISSUE THREAD

**Issue by Centoller** [larryTheCoder/SkyWarsForPE#92]
when winning a game in Skywars the server closes, just like creating a skywars arena (I had to create it manually from the archives) Any solution?

**Comment by larryTheCoder** [comment]
Well there is no solution so far, if you still want to know about this plugin development status, head to #93

**Comment by larryTheCoder** [comment]
The latest version might fix your problems, can you check?

**Comment by supercrafti** [comment]
The mistake is still

**Comment by larryTheCoder** [comment]
Well, fyi, this might be a duplicate of #114, also I tested the plugin today and the issue seems to be solved. Closing this issue to clear old heap issues.
